const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const code = fs.readFileSync(require('path').join(__dirname,'..','core.js'),'utf8');
const sandbox = { module:{exports:{}}, exports:{}, console, Date, Math, Set, JSON };
vm.runInNewContext(code, sandbox, { filename:'core.js' });
const C = sandbox.module.exports;
const state = C.makeDemoState();
const metrics = C.dashboardMetrics(state);
assert(state.properties.length >= 50, 'demo should contain 50+ properties');
assert(state.assets.length >= 50, 'demo should contain installed assets');
assert(metrics.homesUnderCare >= 50, 'homes under care should derive from history');
assert(metrics.identifiedOpportunity > 0, 'engine should identify opportunity value');
assert(state.opportunities.some(o => o.type === 'maintenance_due'), 'maintenance rule should fire');
assert(state.opportunities.some(o => o.type === 'replacement_window'), 'replacement rule should fire');
assert(state.opportunities.some(o => o.type === 'open_estimate'), 'estimate rule should fire');
const before = state.properties.length;
const imported = C.importJobsCSV(state, 'first_name,last_name,email,address,city,state,zip,job_date,job_type,amount\nTest,Owner,test@example.com,999 New St,Bellingham,WA,98225,2025-01-02,Heat Pump Installation,10000');
assert.equal(state.properties.length, before + 1, 'CSV should create a new property');
assert.equal(imported.jobs_imported, 1, 'CSV should import one job');
const open = state.opportunities.find(o => o.status === 'open');
const oldValue = C.dashboardMetrics(state).recoveredRevenue;
C.markBooking(state,{propertyId:open.property_id,opportunityId:open.id});
assert(C.dashboardMetrics(state).recoveredRevenue >= oldValue + open.estimated_value, 'booking should attribute recovered value');
console.log('asktobooked core tests passed', { homes: metrics.homesUnderCare, openValue: metrics.identifiedOpportunity, opportunities: metrics.openOpportunities });
